In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print (a.ndim, a.shape, a.dtype)

In [ ]:
a = np.ones((2, 2,3))
b = np.zeros_like(a)
b

In [57]:
r = np.random.randint(1000, size=(10, 10))
r

array([[265, 829, 752, 440, 327, 109, 961,  74, 860, 252],
       [551, 468, 714, 239, 557, 389, 388, 183, 933, 445],
       [625, 622, 618,  56, 868, 117, 338, 496, 790,  11],
       [880, 394, 953,  25, 490,  54, 481, 455, 621, 571],
       [825, 652, 343, 785, 676, 935, 519,  84, 768, 989],
       [341, 646, 429, 211, 972, 575, 576, 176,  86, 657],
       [142, 551, 963, 981, 156, 637,  10, 114, 570, 546],
       [451, 449, 594, 330, 953, 854,  97, 573, 711, 165],
       [237, 796,  80, 970,  52, 912, 875, 723, 947, 477],
       [466, 369, 135, 780, 906,   4, 446,  53, 650, 604]])

In [99]:
a = np.array([1,2,3,4,5,6])


a = a.reshape(-1,2)
a = a.ravel()
a

array([1, 2, 3, 4, 5, 6])

In [98]:
a = np.arange(10).reshape(5,2)
a = a.transpose((1,0))
array = a

In [101]:
np.savez('data.npz', b=array, a=a)
data = np.load('data.npz')
a = data["b"]
a


array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])